[appendix]
== Instalação de Softwares

[[sec_install_flex]]
=== Instalação do flex

Como é comum para a maioria das ferramentas, para usar o flex é preciso 
instalar o programa antes. Essa instalação geralmente é simples, ou 
mesmo desnecessária por já vir instalado, dependendo do sistema operacional 
utilizado:

Mac OS X:: Em sistemas Mac OS X já vem uma versão do flex instalada. Embora não seja 
uma das versões mais recentes da ferramenta, isso não é um problema 
para o nosso uso. 

Linux:: Em sistemas Linux o flex deve estar disponível como um pacote no sistema 
gerenciador de pacotes da distribuição. Por exemplo, no Ubuntu a instalação pode
ser feita digitando no terminal: +sudo apt-get install flex+ 

Windows:: No Windows o mais adequado é instalar usando um instalador criado 
especificamente para esse sistema operacional, que pode ser encontrado
no endereço http://gnuwin32.sourceforge.net/packages/flex.htm

Você pode testar a instalação do flex passando o parâmetro `--version`,
que irá retornar a versão do flex instalado:

.Testando a instalação do flex no terminal
....
$ flex --version
flex 2.5.35
....

