[appendix]
[[app_code]]
== Códigos completos

Neste capítulo, apresentamos os códigos completos dos arquivos, 
pois durante os capítulos optamos por apresentar, didaticamente, 
apenas os trechos mais relevantes ao que estava sendo explicado.

[[sec_cap2_code]]
=== Capítulo 2

:cap: cap2
:online: {gitrepo}/blob/{edition}/livro/capitulos/code/{cap}
:local: code/{cap}


:srcfile: exp_lexer.c

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----

:srcfile: simples.ll

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----


:srcfile: exp_flex/Makefile

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,make]
.{srcfile}
----
include::{local}/{srcfile}[]
----


:srcfile: exp_flex/exp.ll

[[code_exp_ll]]
==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----

:srcfile: exp_flex/exp_tokens.h

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----


:srcfile: exp_flex/exp_flex.c

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----


:srcfile: minic/minic_tokens.h

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----

:srcfile: minic/lex.ll

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

.{srcfile}
----
include::{local}/{srcfile}[]
----

:srcfile: minic/lex_teste.c

==== {srcfile}

.Código fonte
{online}/{srcfile}[{local}/{srcfile}]

[source,c]
.{srcfile}
----
include::{local}/{srcfile}[]
----
